/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/v1/salud": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Salud
         * @description Verifica la conexión con la base antes de responder (`02` §17).
         */
        get: operations["salud_api_v1_salud_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/version": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Version
         * @description Devuelve la versión de la aplicación en ejecución y la versión mínima
         *     admitida (`02` §11, `02` §6.6, tarea 12.4).
         */
        get: operations["version_api_v1_version_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Login */
        post: operations["login_api_v1_auth_login_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/refresh": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Refresh */
        post: operations["refresh_api_v1_auth_refresh_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/logout": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Logout */
        post: operations["logout_api_v1_auth_logout_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/identidad/dispositivos": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Listar Dispositivos
         * @description Escenario "El listado incluye solo los dispositivos propios": la
         *     organización es la del token, no puede pedirse otra (tarea 10.4).
         */
        get: operations["listar_dispositivos_api_v1_identidad_dispositivos_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/identidad/dispositivos/{dispositivo_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /**
         * Revocar Dispositivo
         * @description Change 04, grupo 11 (`design.md` D7): delega en el bus de comandos
         *     (`DISPOSITIVO_REVOCAR`, `identidad/commands.py`). `RecursoNoEncontradoError`
         *     (404, SEG-07) si el handler rechaza porque `dispositivo_id` no pertenece
         *     a `entrada.contexto.organizacion_id` (INV-21) -- nunca un 204 silencioso
         *     (spec `dispositivos`, escenario "Revocar un dispositivo de otra
         *     organización no lo encuentra").
         */
        delete: operations["revocar_dispositivo_api_v1_identidad_dispositivos__dispositivo_id__delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/identidad/usuarios": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Listar Usuarios
         * @description Tarea 10.8, escenario "La contraseña no se puede recuperar del
         *     sistema": ninguna vía de lectura de usuario expone `password_hash`.
         */
        get: operations["listar_usuarios_api_v1_identidad_usuarios_get"];
        put?: never;
        /**
         * Crear Usuario
         * @description Change 04, grupo 11 (`design.md` D7): delega en el bus de comandos
         *     (`USUARIO_CREAR`, `identidad/commands.py`) en vez de llamar directo a
         *     `identidad_service.crear_usuario` (deuda nominada por el change 03, D6).
         *     `RecursoNoEncontradoError` si `rol_id` no pertenece a
         *     `entrada.contexto.organizacion_id` (SEG-07, INV-21, tarea 12.2). Un
         *     reenvío idéntico (mismo `Operation-Id`, mismo contenido) resuelve el
         *     mismo usuario ya creado -- se relee de la base para que la respuesta
         *     sea el estado real, no un valor cacheado del primer intento.
         */
        post: operations["crear_usuario_api_v1_identidad_usuarios_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/identidad/roles/{rol_id}/permisos": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /**
         * Cambiar Composicion Rol
         * @description Change 04, grupo 14 (decisión del usuario 2026-09-22, `tasks.md`
         *     14.3/14.4): delega en el bus de comandos (`ROL_PERMISOS_CAMBIAR`,
         *     `identidad/commands.py`) en vez de llamar directo a
         *     `identidad_service.cambiar_composicion_rol` (deuda encontrada por la
         *     tarea 14.2). `RecursoNoEncontradoError` si `rol_id` no pertenece a
         *     `entrada.contexto.organizacion_id` (SEG-07, INV-21, tarea 10.7). Un
         *     reenvío idéntico resuelve el mismo rol ya modificado -- se relee de la
         *     base para que la respuesta sea el estado real (mismo criterio que
         *     `crear_usuario`).
         */
        put: operations["cambiar_composicion_rol_api_v1_identidad_roles__rol_id__permisos_put"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/identidad/usuarios/{usuario_id}/pin": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Rotar Pin Autorizacion
         * @description Change 04, grupo 11 (`design.md` D7): delega en el bus de comandos
         *     (`PIN_AUTORIZACION_ROTAR`, `identidad/commands.py`). El PIN viaja en el
         *     contenido del comando como texto (igual que en el cuerpo HTTP que ya
         *     recibía) -- `identidad_commands.PinAutorizacionRotarContenidoV1` lo
         *     envuelve en `SecretStr` recién al validarlo contra el esquema
         *     (`registro.validar_contenido`); `RecursoNoEncontradoError` si
         *     `usuario_id` no pertenece a `entrada.contexto.organizacion_id` (SEG-07,
         *     INV-21). El PIN nunca aparece en la respuesta (`status_code=204`, sin
         *     cuerpo).
         */
        post: operations["rotar_pin_autorizacion_api_v1_identidad_usuarios__usuario_id__pin_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/identidad/usuarios/{usuario_id}/desbloqueo": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Desbloquear Usuario
         * @description Desbloqueo manual de un usuario bloqueado por intentos (tarea 11.4,
         *     `ADR-018`). Change 04, grupo 14 (decisión del usuario 2026-09-22,
         *     `tasks.md` 14.5/14.6): delega en el bus de comandos
         *     (`USUARIO_DESBLOQUEAR`, `identidad/commands.py`). `RecursoNoEncontradoError`
         *     si `usuario_id` no pertenece a `entrada.contexto.organizacion_id`
         *     (SEG-07, INV-21).
         */
        post: operations["desbloquear_usuario_api_v1_identidad_usuarios__usuario_id__desbloqueo_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/catalogo/categorias": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Listar Categorias */
        get: operations["listar_categorias_api_v1_catalogo_categorias_get"];
        put?: never;
        /** Crear Categoria */
        post: operations["crear_categoria_api_v1_catalogo_categorias_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/catalogo/categorias/{categoria_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /** Modificar Categoria */
        put: operations["modificar_categoria_api_v1_catalogo_categorias__categoria_id__put"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/catalogo/marcas": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Listar Marcas */
        get: operations["listar_marcas_api_v1_catalogo_marcas_get"];
        put?: never;
        /** Crear Marca */
        post: operations["crear_marca_api_v1_catalogo_marcas_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/catalogo/marcas/{marca_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /** Modificar Marca */
        put: operations["modificar_marca_api_v1_catalogo_marcas__marca_id__put"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/catalogo/productos": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Listar Productos */
        get: operations["listar_productos_api_v1_catalogo_productos_get"];
        put?: never;
        /** Crear Producto */
        post: operations["crear_producto_api_v1_catalogo_productos_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/catalogo/productos/{producto_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Obtener Producto
         * @description 404 (INV-21/SEG-07) si `producto_id` no existe en
         *     `contexto.organizacion_id` o pertenece a otra organización.
         */
        get: operations["obtener_producto_api_v1_catalogo_productos__producto_id__get"];
        /** Modificar Producto */
        put: operations["modificar_producto_api_v1_catalogo_productos__producto_id__put"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/catalogo/productos/{producto_id}/presentaciones": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Agregar Presentacion */
        post: operations["agregar_presentacion_api_v1_catalogo_productos__producto_id__presentaciones_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/catalogo/presentaciones/{presentacion_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /** Modificar Presentacion */
        put: operations["modificar_presentacion_api_v1_catalogo_presentaciones__presentacion_id__put"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/catalogo/productos/{producto_id}/referencia": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /** Cambiar Referencia */
        put: operations["cambiar_referencia_api_v1_catalogo_productos__producto_id__referencia_put"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/configuracion/alicuotas": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Listar Alicuotas */
        get: operations["listar_alicuotas_api_v1_configuracion_alicuotas_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/sync/comandos": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Sincronizar Lote
         * @description Procesa el lote de la cola del dispositivo (`02` §6.4, tareas 8.1 a
         *     8.10). `organizacion_id`, `usuario_id` y `dispositivo_id` de la sesión
         *     vienen siempre del token (`contexto`), nunca del cuerpo -- cada ítem
         *     declara los suyos solo para que `sync_service.procesar_lote` pueda
         *     rechazar una cola ajena (`ColaAjenaError`) en vez de reatribuirla en
         *     silencio.
         */
        post: operations["sincronizar_lote_api_v1_sync_comandos_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** AlicuotaResponse */
        AlicuotaResponse: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Nombre */
            nombre: string;
            /** Valor */
            valor: string;
            /** Activo */
            activo: boolean;
        };
        /** CategoriaCrearRequest */
        CategoriaCrearRequest: {
            /** Nombre */
            nombre: string;
        };
        /** CategoriaModificarRequest */
        CategoriaModificarRequest: {
            /** Nombre */
            nombre: string;
            /** Activo */
            activo: boolean;
        };
        /** CategoriaResponse */
        CategoriaResponse: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Nombre */
            nombre: string;
            /** Activo */
            activo: boolean;
            /**
             * Creado En
             * Format: date-time
             */
            creado_en: string;
            /**
             * Actualizado En
             * Format: date-time
             */
            actualizado_en: string;
        };
        /** ComposicionRolRequest */
        ComposicionRolRequest: {
            /** Permisos */
            permisos: string[];
        };
        /** CrearUsuarioRequest */
        CrearUsuarioRequest: {
            /** Usuario */
            usuario: string;
            /** Nombre */
            nombre: string;
            /** Email */
            email: string | null;
            /** Password */
            password: string;
            /**
             * Rol Id
             * Format: uuid
             */
            rol_id: string;
        };
        /** DispositivoResponse */
        DispositivoResponse: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Nombre */
            nombre: string;
            /** Prefijo */
            prefijo: string;
            /** Estado */
            estado: string;
            /** Ultimo Correlativo */
            ultimo_correlativo: number;
            /** Revocado En */
            revocado_en: string | null;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /**
         * ItemLoteComandoRequest
         * @description Un comando de la cola local (`02` §13.2 `cola`), tal como el
         *     dispositivo lo generó. `usuario_id`/`dispositivo_id` son los que
         *     declaró al generarlo -- el servidor los compara contra la sesión que
         *     sincroniza (`ColaAjenaError`, tarea 8.5), nunca los usa tal cual para
         *     construir el sobre sin esa verificación.
         */
        ItemLoteComandoRequest: {
            /**
             * Operation Id
             * Format: uuid
             */
            operation_id: string;
            /** Tipo */
            tipo: string;
            /** Version */
            version: number;
            /**
             * Modo
             * @enum {string}
             */
            modo: "ONLINE" | "OFFLINE";
            /**
             * Usuario Id
             * Format: uuid
             */
            usuario_id: string;
            /**
             * Dispositivo Id
             * Format: uuid
             */
            dispositivo_id: string;
            /**
             * Occurred At
             * Format: date-time
             */
            occurred_at: string;
            /** Secuencia */
            secuencia: number;
            /** App Version */
            app_version: string;
            /** Contenido */
            contenido?: {
                [key: string]: unknown;
            };
            /** Jornada Id */
            jornada_id?: string | null;
        };
        /** LoginRequest */
        LoginRequest: {
            /** Organizacion Slug */
            organizacion_slug: string;
            /** Usuario */
            usuario: string;
            /** Contrasena */
            contrasena: string;
            /**
             * Dispositivo Id
             * Format: uuid
             */
            dispositivo_id: string;
            /** Nombre Dispositivo */
            nombre_dispositivo: string;
        };
        /**
         * LoteComandosRequest
         * @description `02` §6.4: hasta 50 comandos por lote; un lote vacío es válido
         *     (tarea 8.2). `max_length=50` rechaza un lote de 51 con un 422 de
         *     Pydantic ANTES de que la ruta se ejecute -- ninguno de sus comandos
         *     llega a procesarse, que es exactamente lo que pide el escenario "Un
         *     lote que excede el máximo se rechaza entero".
         */
        LoteComandosRequest: {
            /** Items */
            items?: components["schemas"]["ItemLoteComandoRequest"][];
        };
        /** LoteComandosResponse */
        LoteComandosResponse: {
            /** Resultados */
            resultados: components["schemas"]["ResultadoItemLoteResponse"][];
        };
        /** MarcaCrearRequest */
        MarcaCrearRequest: {
            /** Nombre */
            nombre: string;
        };
        /** MarcaModificarRequest */
        MarcaModificarRequest: {
            /** Nombre */
            nombre: string;
            /** Activo */
            activo: boolean;
        };
        /** MarcaResponse */
        MarcaResponse: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Nombre */
            nombre: string;
            /** Activo */
            activo: boolean;
            /**
             * Creado En
             * Format: date-time
             */
            creado_en: string;
            /**
             * Actualizado En
             * Format: date-time
             */
            actualizado_en: string;
        };
        /** PaginaAlicuotas */
        PaginaAlicuotas: {
            /** Items */
            items: components["schemas"]["AlicuotaResponse"][];
            /** Cursor Siguiente */
            cursor_siguiente: string | null;
        };
        /** PaginaCategorias */
        PaginaCategorias: {
            /** Items */
            items: components["schemas"]["CategoriaResponse"][];
            /** Cursor Siguiente */
            cursor_siguiente: string | null;
        };
        /** PaginaMarcas */
        PaginaMarcas: {
            /** Items */
            items: components["schemas"]["MarcaResponse"][];
            /** Cursor Siguiente */
            cursor_siguiente: string | null;
        };
        /** PaginaProductos */
        PaginaProductos: {
            /** Items */
            items: components["schemas"]["ProductoResponse"][];
            /** Cursor Siguiente */
            cursor_siguiente: string | null;
        };
        /** PresentacionAgregarRequest */
        PresentacionAgregarRequest: {
            /** Nombre */
            nombre: string;
            /** Unidades Base */
            unidades_base: number;
            /** Usar En Venta */
            usar_en_venta: boolean;
            /** Usar En Compra */
            usar_en_compra: boolean;
        };
        /**
         * PresentacionInicialRequest
         * @description Presentación inicial dentro de un `ProductoCrearRequest` (CAT-02,
         *     CAT-03: el alta ya trae sus presentaciones, exactamente una de
         *     referencia).
         */
        PresentacionInicialRequest: {
            /** Nombre */
            nombre: string;
            /** Unidades Base */
            unidades_base: number;
            /** Usar En Venta */
            usar_en_venta: boolean;
            /** Usar En Compra */
            usar_en_compra: boolean;
            /** Es Referencia */
            es_referencia: boolean;
        };
        /** PresentacionModificarRequest */
        PresentacionModificarRequest: {
            /** Nombre */
            nombre: string;
            /** Unidades Base */
            unidades_base: number;
            /** Usar En Venta */
            usar_en_venta: boolean;
            /** Usar En Compra */
            usar_en_compra: boolean;
            /** Activo */
            activo: boolean;
        };
        /** PresentacionReferenciaCambiarRequest */
        PresentacionReferenciaCambiarRequest: {
            /**
             * Presentacion Id
             * Format: uuid
             */
            presentacion_id: string;
        };
        /** PresentacionResponse */
        PresentacionResponse: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /**
             * Producto Id
             * Format: uuid
             */
            producto_id: string;
            /** Nombre */
            nombre: string;
            /** Unidades Base */
            unidades_base: number;
            /** Usar En Venta */
            usar_en_venta: boolean;
            /** Usar En Compra */
            usar_en_compra: boolean;
            /** Es Referencia */
            es_referencia: boolean;
            /** Activo */
            activo: boolean;
            /**
             * Creado En
             * Format: date-time
             */
            creado_en: string;
            /**
             * Actualizado En
             * Format: date-time
             */
            actualizado_en: string;
        };
        /** ProductoCrearRequest */
        ProductoCrearRequest: {
            /** Codigo */
            codigo: string;
            /** Nombre */
            nombre: string;
            /**
             * Categoria Id
             * Format: uuid
             */
            categoria_id: string;
            /** Marca Id */
            marca_id?: string | null;
            /** Unidad Base */
            unidad_base: string;
            /**
             * Alicuota Id
             * Format: uuid
             */
            alicuota_id: string;
            /** Presentaciones */
            presentaciones: components["schemas"]["PresentacionInicialRequest"][];
        };
        /** ProductoDetalleResponse */
        ProductoDetalleResponse: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Codigo */
            codigo: string;
            /** Nombre */
            nombre: string;
            /**
             * Categoria Id
             * Format: uuid
             */
            categoria_id: string;
            /** Marca Id */
            marca_id: string | null;
            /** Unidad Base */
            unidad_base: string;
            /**
             * Alicuota Id
             * Format: uuid
             */
            alicuota_id: string;
            /** Activo */
            activo: boolean;
            /**
             * Creado En
             * Format: date-time
             */
            creado_en: string;
            /**
             * Actualizado En
             * Format: date-time
             */
            actualizado_en: string;
            /** Presentaciones */
            presentaciones: components["schemas"]["PresentacionResponse"][];
        };
        /** ProductoModificarRequest */
        ProductoModificarRequest: {
            /** Codigo */
            codigo: string;
            /** Nombre */
            nombre: string;
            /**
             * Categoria Id
             * Format: uuid
             */
            categoria_id: string;
            /** Marca Id */
            marca_id?: string | null;
            /** Unidad Base */
            unidad_base: string;
            /**
             * Alicuota Id
             * Format: uuid
             */
            alicuota_id: string;
            /** Activo */
            activo: boolean;
        };
        /**
         * ProductoResponse
         * @description Fila de listado (tarea 9.2): sin presentaciones -- para el detalle
         *     completo (incluidas sus presentaciones) ver `ProductoDetalleResponse`.
         */
        ProductoResponse: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Codigo */
            codigo: string;
            /** Nombre */
            nombre: string;
            /**
             * Categoria Id
             * Format: uuid
             */
            categoria_id: string;
            /** Marca Id */
            marca_id: string | null;
            /** Unidad Base */
            unidad_base: string;
            /**
             * Alicuota Id
             * Format: uuid
             */
            alicuota_id: string;
            /** Activo */
            activo: boolean;
            /**
             * Creado En
             * Format: date-time
             */
            creado_en: string;
            /**
             * Actualizado En
             * Format: date-time
             */
            actualizado_en: string;
        };
        /** RefreshRequest */
        RefreshRequest: {
            /**
             * Dispositivo Id
             * Format: uuid
             */
            dispositivo_id: string;
        };
        /** ResultadoItemLoteResponse */
        ResultadoItemLoteResponse: {
            /**
             * Operation Id
             * Format: uuid
             */
            operation_id: string;
            /** Estado */
            estado: string;
            /** Resultado */
            resultado: {
                [key: string]: unknown;
            } | null;
            /** Error Codigo */
            error_codigo: string | null;
        };
        /** RolResponse */
        RolResponse: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Nombre */
            nombre: string;
            /** Permisos */
            permisos: string[];
        };
        /** RotarPinRequest */
        RotarPinRequest: {
            /** Pin */
            pin: string;
        };
        /** SaludRespuesta */
        SaludRespuesta: {
            /**
             * Estado
             * @enum {string}
             */
            estado: "ok" | "error";
        };
        /** TokenResponse */
        TokenResponse: {
            /** Access Token */
            access_token: string;
            /**
             * Token Type
             * @default bearer
             * @constant
             */
            token_type: "bearer";
        };
        /**
         * UsuarioResponse
         * @description Tarea 10.8: sin `password_hash` ni las tres columnas del PIN de
         *     autorización -- Pydantic solo serializa los campos declarados acá, así
         *     que omitirlos de este modelo es la garantía, no un filtro posterior.
         */
        UsuarioResponse: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Usuario */
            usuario: string;
            /** Nombre */
            nombre: string;
            /** Email */
            email: string | null;
            /**
             * Rol Id
             * Format: uuid
             */
            rol_id: string;
            /** Estado */
            estado: string;
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
            /** Input */
            input?: unknown;
            /** Context */
            ctx?: Record<string, never>;
        };
        /** VersionRespuesta */
        VersionRespuesta: {
            /** Version */
            version: string;
            /** App Version Minima */
            app_version_minima?: string | null;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    salud_api_v1_salud_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SaludRespuesta"];
                };
            };
        };
    };
    version_api_v1_version_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["VersionRespuesta"];
                };
            };
        };
    };
    login_api_v1_auth_login_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["LoginRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TokenResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    refresh_api_v1_auth_refresh_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: {
                refresh_token?: string | null;
            };
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RefreshRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TokenResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    logout_api_v1_auth_logout_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: {
                refresh_token?: string | null;
            };
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    listar_dispositivos_api_v1_identidad_dispositivos_get: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DispositivoResponse"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    revocar_dispositivo_api_v1_identidad_dispositivos__dispositivo_id__delete: {
        parameters: {
            query?: never;
            header?: {
                "Operation-Id"?: string | null;
                authorization?: string | null;
            };
            path: {
                dispositivo_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    listar_usuarios_api_v1_identidad_usuarios_get: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UsuarioResponse"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    crear_usuario_api_v1_identidad_usuarios_post: {
        parameters: {
            query?: never;
            header?: {
                "Operation-Id"?: string | null;
                authorization?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CrearUsuarioRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UsuarioResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    cambiar_composicion_rol_api_v1_identidad_roles__rol_id__permisos_put: {
        parameters: {
            query?: never;
            header?: {
                "Operation-Id"?: string | null;
                authorization?: string | null;
            };
            path: {
                rol_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ComposicionRolRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RolResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    rotar_pin_autorizacion_api_v1_identidad_usuarios__usuario_id__pin_post: {
        parameters: {
            query?: never;
            header?: {
                "Operation-Id"?: string | null;
                authorization?: string | null;
            };
            path: {
                usuario_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RotarPinRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    desbloquear_usuario_api_v1_identidad_usuarios__usuario_id__desbloqueo_post: {
        parameters: {
            query?: never;
            header?: {
                "Operation-Id"?: string | null;
                authorization?: string | null;
            };
            path: {
                usuario_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    listar_categorias_api_v1_catalogo_categorias_get: {
        parameters: {
            query?: {
                limite?: number;
                cursor?: string | null;
                solo_activas?: boolean;
            };
            header?: {
                authorization?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PaginaCategorias"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    crear_categoria_api_v1_catalogo_categorias_post: {
        parameters: {
            query?: never;
            header?: {
                "Operation-Id"?: string | null;
                authorization?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CategoriaCrearRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CategoriaResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    modificar_categoria_api_v1_catalogo_categorias__categoria_id__put: {
        parameters: {
            query?: never;
            header?: {
                "Operation-Id"?: string | null;
                authorization?: string | null;
            };
            path: {
                categoria_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CategoriaModificarRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CategoriaResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    listar_marcas_api_v1_catalogo_marcas_get: {
        parameters: {
            query?: {
                limite?: number;
                cursor?: string | null;
                solo_activas?: boolean;
            };
            header?: {
                authorization?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PaginaMarcas"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    crear_marca_api_v1_catalogo_marcas_post: {
        parameters: {
            query?: never;
            header?: {
                "Operation-Id"?: string | null;
                authorization?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["MarcaCrearRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MarcaResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    modificar_marca_api_v1_catalogo_marcas__marca_id__put: {
        parameters: {
            query?: never;
            header?: {
                "Operation-Id"?: string | null;
                authorization?: string | null;
            };
            path: {
                marca_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["MarcaModificarRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MarcaResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    listar_productos_api_v1_catalogo_productos_get: {
        parameters: {
            query?: {
                limite?: number;
                cursor?: string | null;
                texto?: string | null;
                categoria_id?: string | null;
                marca_id?: string | null;
                activo?: boolean | null;
            };
            header?: {
                authorization?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PaginaProductos"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    crear_producto_api_v1_catalogo_productos_post: {
        parameters: {
            query?: never;
            header?: {
                "Operation-Id"?: string | null;
                authorization?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ProductoCrearRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProductoDetalleResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    obtener_producto_api_v1_catalogo_productos__producto_id__get: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path: {
                producto_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProductoDetalleResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    modificar_producto_api_v1_catalogo_productos__producto_id__put: {
        parameters: {
            query?: never;
            header?: {
                "Operation-Id"?: string | null;
                authorization?: string | null;
            };
            path: {
                producto_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ProductoModificarRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProductoResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    agregar_presentacion_api_v1_catalogo_productos__producto_id__presentaciones_post: {
        parameters: {
            query?: never;
            header?: {
                "Operation-Id"?: string | null;
                authorization?: string | null;
            };
            path: {
                producto_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PresentacionAgregarRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PresentacionResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    modificar_presentacion_api_v1_catalogo_presentaciones__presentacion_id__put: {
        parameters: {
            query?: never;
            header?: {
                "Operation-Id"?: string | null;
                authorization?: string | null;
            };
            path: {
                presentacion_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PresentacionModificarRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PresentacionResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    cambiar_referencia_api_v1_catalogo_productos__producto_id__referencia_put: {
        parameters: {
            query?: never;
            header?: {
                "Operation-Id"?: string | null;
                authorization?: string | null;
            };
            path: {
                producto_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PresentacionReferenciaCambiarRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PresentacionResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    listar_alicuotas_api_v1_configuracion_alicuotas_get: {
        parameters: {
            query?: {
                limite?: number;
                cursor?: string | null;
            };
            header?: {
                authorization?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PaginaAlicuotas"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    sincronizar_lote_api_v1_sync_comandos_post: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["LoteComandosRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LoteComandosResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
}
