/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/v1/salud": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Salud
         * @description Verifica la conexión con la base antes de responder (`02` §17).
         */
        get: operations["salud_api_v1_salud_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/version": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Version
         * @description Devuelve la versión de la aplicación en ejecución y la versión mínima
         *     admitida (`02` §11, `02` §6.6, tarea 12.4).
         */
        get: operations["version_api_v1_version_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Login */
        post: operations["login_api_v1_auth_login_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/refresh": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Refresh */
        post: operations["refresh_api_v1_auth_refresh_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/logout": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Logout */
        post: operations["logout_api_v1_auth_logout_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/identidad/dispositivos": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Listar Dispositivos
         * @description Escenario "El listado incluye solo los dispositivos propios": la
         *     organización es la del token, no puede pedirse otra (tarea 10.4).
         */
        get: operations["listar_dispositivos_api_v1_identidad_dispositivos_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/identidad/dispositivos/{dispositivo_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /**
         * Revocar Dispositivo
         * @description Change 04, grupo 11 (`design.md` D7): delega en el bus de comandos
         *     (`DISPOSITIVO_REVOCAR`, `identidad/commands.py`). `RecursoNoEncontradoError`
         *     (404, SEG-07) si el handler rechaza porque `dispositivo_id` no pertenece
         *     a `entrada.contexto.organizacion_id` (INV-21) -- nunca un 204 silencioso
         *     (spec `dispositivos`, escenario "Revocar un dispositivo de otra
         *     organización no lo encuentra").
         */
        delete: operations["revocar_dispositivo_api_v1_identidad_dispositivos__dispositivo_id__delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/identidad/usuarios": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Listar Usuarios
         * @description Tarea 10.8, escenario "La contraseña no se puede recuperar del
         *     sistema": ninguna vía de lectura de usuario expone `password_hash`.
         */
        get: operations["listar_usuarios_api_v1_identidad_usuarios_get"];
        put?: never;
        /**
         * Crear Usuario
         * @description Change 04, grupo 11 (`design.md` D7): delega en el bus de comandos
         *     (`USUARIO_CREAR`, `identidad/commands.py`) en vez de llamar directo a
         *     `identidad_service.crear_usuario` (deuda nominada por el change 03, D6).
         *     `RecursoNoEncontradoError` si `rol_id` no pertenece a
         *     `entrada.contexto.organizacion_id` (SEG-07, INV-21, tarea 12.2). Un
         *     reenvío idéntico (mismo `Operation-Id`, mismo contenido) resuelve el
         *     mismo usuario ya creado -- se relee de la base para que la respuesta
         *     sea el estado real, no un valor cacheado del primer intento.
         */
        post: operations["crear_usuario_api_v1_identidad_usuarios_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/identidad/roles/{rol_id}/permisos": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /**
         * Cambiar Composicion Rol
         * @description Change 04, grupo 14 (decisión del usuario 2026-09-22, `tasks.md`
         *     14.3/14.4): delega en el bus de comandos (`ROL_PERMISOS_CAMBIAR`,
         *     `identidad/commands.py`) en vez de llamar directo a
         *     `identidad_service.cambiar_composicion_rol` (deuda encontrada por la
         *     tarea 14.2). `RecursoNoEncontradoError` si `rol_id` no pertenece a
         *     `entrada.contexto.organizacion_id` (SEG-07, INV-21, tarea 10.7). Un
         *     reenvío idéntico resuelve el mismo rol ya modificado -- se relee de la
         *     base para que la respuesta sea el estado real (mismo criterio que
         *     `crear_usuario`).
         */
        put: operations["cambiar_composicion_rol_api_v1_identidad_roles__rol_id__permisos_put"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/identidad/usuarios/{usuario_id}/pin": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Rotar Pin Autorizacion
         * @description Change 04, grupo 11 (`design.md` D7): delega en el bus de comandos
         *     (`PIN_AUTORIZACION_ROTAR`, `identidad/commands.py`). El PIN viaja en el
         *     contenido del comando como texto (igual que en el cuerpo HTTP que ya
         *     recibía) -- `identidad_commands.PinAutorizacionRotarContenidoV1` lo
         *     envuelve en `SecretStr` recién al validarlo contra el esquema
         *     (`registro.validar_contenido`); `RecursoNoEncontradoError` si
         *     `usuario_id` no pertenece a `entrada.contexto.organizacion_id` (SEG-07,
         *     INV-21). El PIN nunca aparece en la respuesta (`status_code=204`, sin
         *     cuerpo).
         */
        post: operations["rotar_pin_autorizacion_api_v1_identidad_usuarios__usuario_id__pin_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/identidad/usuarios/{usuario_id}/desbloqueo": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Desbloquear Usuario
         * @description Desbloqueo manual de un usuario bloqueado por intentos (tarea 11.4,
         *     `ADR-018`). Change 04, grupo 14 (decisión del usuario 2026-09-22,
         *     `tasks.md` 14.5/14.6): delega en el bus de comandos
         *     (`USUARIO_DESBLOQUEAR`, `identidad/commands.py`). `RecursoNoEncontradoError`
         *     si `usuario_id` no pertenece a `entrada.contexto.organizacion_id`
         *     (SEG-07, INV-21).
         */
        post: operations["desbloquear_usuario_api_v1_identidad_usuarios__usuario_id__desbloqueo_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/yo": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Obtener Yo
         * @description Datos de la propia sesión (D1, ADR-027). Delega enteramente en
         *     `identidad_service.obtener_yo`: ninguna lógica de permisos o de sesión
         *     habilitada se duplica acá. `AccessTokenInvalidoError` (usuario
         *     inexistente, `INACTIVO`, o con rol inactivo -- ADR-028 D9) se propaga
         *     tal cual; el manejador genérico de `DomainError` la traduce a 401
         *     `IDENTIDAD_ACCESS_TOKEN_INVALIDO` (D1).
         */
        get: operations["obtener_yo_api_v1_yo_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/catalogo/categorias": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Listar Categorias */
        get: operations["listar_categorias_api_v1_catalogo_categorias_get"];
        put?: never;
        /** Crear Categoria */
        post: operations["crear_categoria_api_v1_catalogo_categorias_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/catalogo/categorias/{categoria_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /** Modificar Categoria */
        put: operations["modificar_categoria_api_v1_catalogo_categorias__categoria_id__put"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/catalogo/marcas": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Listar Marcas */
        get: operations["listar_marcas_api_v1_catalogo_marcas_get"];
        put?: never;
        /** Crear Marca */
        post: operations["crear_marca_api_v1_catalogo_marcas_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/catalogo/marcas/{marca_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /** Modificar Marca */
        put: operations["modificar_marca_api_v1_catalogo_marcas__marca_id__put"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/catalogo/productos": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Listar Productos */
        get: operations["listar_productos_api_v1_catalogo_productos_get"];
        put?: never;
        /** Crear Producto */
        post: operations["crear_producto_api_v1_catalogo_productos_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/catalogo/productos/{producto_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Obtener Producto
         * @description 404 (INV-21/SEG-07) si `producto_id` no existe en
         *     `contexto.organizacion_id` o pertenece a otra organización.
         */
        get: operations["obtener_producto_api_v1_catalogo_productos__producto_id__get"];
        /** Modificar Producto */
        put: operations["modificar_producto_api_v1_catalogo_productos__producto_id__put"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/catalogo/productos/{producto_id}/presentaciones": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Agregar Presentacion */
        post: operations["agregar_presentacion_api_v1_catalogo_productos__producto_id__presentaciones_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/catalogo/presentaciones/{presentacion_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /** Modificar Presentacion */
        put: operations["modificar_presentacion_api_v1_catalogo_presentaciones__presentacion_id__put"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/catalogo/productos/{producto_id}/referencia": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /** Cambiar Referencia */
        put: operations["cambiar_referencia_api_v1_catalogo_productos__producto_id__referencia_put"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/configuracion/alicuotas": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Listar Alicuotas */
        get: operations["listar_alicuotas_api_v1_configuracion_alicuotas_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/proveedores": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Listar Proveedores */
        get: operations["listar_proveedores_api_v1_proveedores_get"];
        put?: never;
        /** Crear Proveedor */
        post: operations["crear_proveedor_api_v1_proveedores_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/proveedores/{proveedor_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Obtener Proveedor */
        get: operations["obtener_proveedor_api_v1_proveedores__proveedor_id__get"];
        /** Modificar Proveedor */
        put: operations["modificar_proveedor_api_v1_proveedores__proveedor_id__put"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/proveedores/opciones": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Listar Opciones De Proveedores */
        get: operations["listar_opciones_de_proveedores_api_v1_proveedores_opciones_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/costos": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Informar Costos */
        post: operations["informar_costos_api_v1_costos_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/costos/productos/{producto_id}/vigente": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Obtener Costo Vigente
         * @description P7 (aprobado 2026-09-24): 200 con `costo: null` si el producto no
         *     tiene costo vigente para `fecha`; 404 solo si `producto_id` no existe
         *     en la organización o es ajeno (INV-21).
         *
         *     P11 (`contrato-api.md`, aprobado en la verificación manual 13.5,
         *     opción B): suma `por_presentacion` -- el último costo informado (D4)
         *     de CADA presentación con costo a `fecha`, resuelto con la única
         *     consulta de `proveedores_service.listar_ultimo_costo_por_presentacion`
         *     (nunca trayendo el historial completo a Python). Los nombres de
         *     usuario se resuelven por lote junto con los del costo vigente (evita
         *     N+1); la lista se ordena por `presentacion_nombre` una vez resueltos
         *     los nombres para mostrar (mismo patrón que P4).
         */
        get: operations["obtener_costo_vigente_api_v1_costos_productos__producto_id__vigente_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/costos/productos/{producto_id}/historial": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Listar Historial De Costos */
        get: operations["listar_historial_de_costos_api_v1_costos_productos__producto_id__historial_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/sync/comandos": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Sincronizar Lote
         * @description Procesa el lote de la cola del dispositivo (`02` §6.4, tareas 8.1 a
         *     8.10). `organizacion_id`, `usuario_id` y `dispositivo_id` de la sesión
         *     vienen siempre del token (`contexto`), nunca del cuerpo -- cada ítem
         *     declara los suyos solo para que `sync_service.procesar_lote` pueda
         *     rechazar una cola ajena (`ColaAjenaError`) en vez de reatribuirla en
         *     silencio.
         */
        post: operations["sincronizar_lote_api_v1_sync_comandos_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** AlicuotaResponse */
        AlicuotaResponse: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Nombre */
            nombre: string;
            /** Valor */
            valor: string;
            /** Activo */
            activo: boolean;
        };
        /** CategoriaCrearRequest */
        CategoriaCrearRequest: {
            /** Nombre */
            nombre: string;
        };
        /** CategoriaModificarRequest */
        CategoriaModificarRequest: {
            /** Nombre */
            nombre: string;
            /** Activo */
            activo: boolean;
        };
        /** CategoriaResponse */
        CategoriaResponse: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Nombre */
            nombre: string;
            /** Activo */
            activo: boolean;
            /**
             * Creado En
             * Format: date-time
             */
            creado_en: string;
            /**
             * Actualizado En
             * Format: date-time
             */
            actualizado_en: string;
        };
        /** ComposicionRolRequest */
        ComposicionRolRequest: {
            /** Permisos */
            permisos: string[];
        };
        /**
         * CostoDelLoteRequest
         * @description Un costo dentro del lote de `POST /costos` (D12). `valor` y
         *     `bonificacion` viajan como string estricto (P3); la cantidad de
         *     decimales la valida el dominio, no el patrón de este campo.
         */
        CostoDelLoteRequest: {
            /**
             * Producto Id
             * Format: uuid
             */
            producto_id: string;
            /**
             * Presentacion Id
             * Format: uuid
             */
            presentacion_id: string;
            /** Valor */
            valor: string;
            /** Incluye Iva */
            incluye_iva: boolean;
            /**
             * Bonificacion
             * @default 0
             */
            bonificacion: string;
            /**
             * Vigencia Desde
             * Format: date
             */
            vigencia_desde: string;
            /** Observacion */
            observacion?: string | null;
        };
        /**
         * CostoDelResultadoResponse
         * @description Un elemento de la respuesta de `POST /costos` (P6, aprobado
         *     2026-09-24): sale de `comando.resultado`, no de una relectura de las
         *     filas -- un reenvío idempotente del mismo `Operation-Id` devuelve
         *     exactamente lo mismo.
         */
        CostoDelResultadoResponse: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Costo Base */
            costo_base: string;
        };
        /**
         * CostoInformadoResponse
         * @description Respuesta de `GET .../vigente` y `GET .../historial` (`contrato-
         *     api.md` §2.2). `proveedor_nombre` y `presentacion_nombre` (P4, aprobado
         *     2026-09-24) se resuelven en `api.py`, no vienen de `model_validate`
         *     directo del modelo `CostoInformado` -- por eso este esquema NO declara
         *     `from_attributes`: `api.py` arma cada instancia explícitamente.
         */
        CostoInformadoResponse: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /**
             * Proveedor Id
             * Format: uuid
             */
            proveedor_id: string;
            /**
             * Producto Id
             * Format: uuid
             */
            producto_id: string;
            /**
             * Presentacion Id
             * Format: uuid
             */
            presentacion_id: string;
            /** Valor */
            valor: string;
            /** Incluye Iva */
            incluye_iva: boolean;
            /** Bonificacion */
            bonificacion: string;
            /** Alicuota Aplicada */
            alicuota_aplicada: string;
            /** Costo Base */
            costo_base: string;
            /**
             * Vigencia Desde
             * Format: date
             */
            vigencia_desde: string;
            /** Observacion */
            observacion: string | null;
            /**
             * Usuario Id
             * Format: uuid
             */
            usuario_id: string;
            /**
             * Operation Id
             * Format: uuid
             */
            operation_id: string;
            /**
             * Creado En
             * Format: date-time
             */
            creado_en: string;
            /** Proveedor Nombre */
            proveedor_nombre: string;
            /** Presentacion Nombre */
            presentacion_nombre: string;
            /** Usuario Nombre */
            usuario_nombre: string;
        };
        /** CostoInformarRequest */
        CostoInformarRequest: {
            /**
             * Proveedor Id
             * Format: uuid
             */
            proveedor_id: string;
            /** Costos */
            costos: components["schemas"]["CostoDelLoteRequest"][];
        };
        /** CostoInformarResponse */
        CostoInformarResponse: {
            /** Costos */
            costos: components["schemas"]["CostoDelResultadoResponse"][];
        };
        /**
         * CostoVigenteResponse
         * @description `GET .../vigente` (P7, aprobado 2026-09-24): 200 siempre que el
         *     producto exista en la organización, con `costo: null` cuando no hay
         *     costo vigente para `fecha` -- el 404 queda solo para un producto
         *     inexistente o ajeno (INV-21).
         */
        CostoVigenteResponse: {
            /**
             * Fecha
             * Format: date
             */
            fecha: string;
            costo: components["schemas"]["CostoInformadoResponse"] | null;
            /** Por Presentacion */
            por_presentacion: components["schemas"]["CostoInformadoResponse"][];
        };
        /** CrearUsuarioRequest */
        CrearUsuarioRequest: {
            /** Usuario */
            usuario: string;
            /** Nombre */
            nombre: string;
            /** Email */
            email: string | null;
            /** Password */
            password: string;
            /**
             * Rol Id
             * Format: uuid
             */
            rol_id: string;
        };
        /** DispositivoResponse */
        DispositivoResponse: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Nombre */
            nombre: string;
            /** Prefijo */
            prefijo: string;
            /** Estado */
            estado: string;
            /** Ultimo Correlativo */
            ultimo_correlativo: number;
            /** Revocado En */
            revocado_en: string | null;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /**
         * ItemLoteComandoRequest
         * @description Un comando de la cola local (`02` §13.2 `cola`), tal como el
         *     dispositivo lo generó. `usuario_id`/`dispositivo_id` son los que
         *     declaró al generarlo -- el servidor los compara contra la sesión que
         *     sincroniza (`ColaAjenaError`, tarea 8.5), nunca los usa tal cual para
         *     construir el sobre sin esa verificación.
         */
        ItemLoteComandoRequest: {
            /**
             * Operation Id
             * Format: uuid
             */
            operation_id: string;
            /** Tipo */
            tipo: string;
            /** Version */
            version: number;
            /**
             * Modo
             * @enum {string}
             */
            modo: "ONLINE" | "OFFLINE";
            /**
             * Usuario Id
             * Format: uuid
             */
            usuario_id: string;
            /**
             * Dispositivo Id
             * Format: uuid
             */
            dispositivo_id: string;
            /**
             * Occurred At
             * Format: date-time
             */
            occurred_at: string;
            /** Secuencia */
            secuencia: number;
            /** App Version */
            app_version: string;
            /** Contenido */
            contenido?: {
                [key: string]: unknown;
            };
            /** Jornada Id */
            jornada_id?: string | null;
        };
        /** LoginRequest */
        LoginRequest: {
            /** Organizacion Slug */
            organizacion_slug: string;
            /** Usuario */
            usuario: string;
            /** Contrasena */
            contrasena: string;
            /**
             * Dispositivo Id
             * Format: uuid
             */
            dispositivo_id: string;
            /** Nombre Dispositivo */
            nombre_dispositivo: string;
        };
        /**
         * LoteComandosRequest
         * @description `02` §6.4: hasta 50 comandos por lote; un lote vacío es válido
         *     (tarea 8.2). `max_length=50` rechaza un lote de 51 con un 422 de
         *     Pydantic ANTES de que la ruta se ejecute -- ninguno de sus comandos
         *     llega a procesarse, que es exactamente lo que pide el escenario "Un
         *     lote que excede el máximo se rechaza entero".
         */
        LoteComandosRequest: {
            /** Items */
            items?: components["schemas"]["ItemLoteComandoRequest"][];
        };
        /** LoteComandosResponse */
        LoteComandosResponse: {
            /** Resultados */
            resultados: components["schemas"]["ResultadoItemLoteResponse"][];
        };
        /** MarcaCrearRequest */
        MarcaCrearRequest: {
            /** Nombre */
            nombre: string;
        };
        /** MarcaModificarRequest */
        MarcaModificarRequest: {
            /** Nombre */
            nombre: string;
            /** Activo */
            activo: boolean;
        };
        /** MarcaResponse */
        MarcaResponse: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Nombre */
            nombre: string;
            /** Activo */
            activo: boolean;
            /**
             * Creado En
             * Format: date-time
             */
            creado_en: string;
            /**
             * Actualizado En
             * Format: date-time
             */
            actualizado_en: string;
        };
        /** OrganizacionYoResponse */
        OrganizacionYoResponse: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Nombre */
            nombre: string;
        };
        /** PaginaAlicuotas */
        PaginaAlicuotas: {
            /** Items */
            items: components["schemas"]["AlicuotaResponse"][];
            /** Cursor Siguiente */
            cursor_siguiente: string | null;
        };
        /** PaginaCategorias */
        PaginaCategorias: {
            /** Items */
            items: components["schemas"]["CategoriaResponse"][];
            /** Cursor Siguiente */
            cursor_siguiente: string | null;
        };
        /** PaginaCostosInformados */
        PaginaCostosInformados: {
            /** Items */
            items: components["schemas"]["CostoInformadoResponse"][];
            /** Cursor Siguiente */
            cursor_siguiente: string | null;
        };
        /** PaginaMarcas */
        PaginaMarcas: {
            /** Items */
            items: components["schemas"]["MarcaResponse"][];
            /** Cursor Siguiente */
            cursor_siguiente: string | null;
        };
        /** PaginaProductos */
        PaginaProductos: {
            /** Items */
            items: components["schemas"]["ProductoResponse"][];
            /** Cursor Siguiente */
            cursor_siguiente: string | null;
        };
        /**
         * PaginaProveedorOpciones
         * @description Paginada (`contrato-api.md` P2, aprobado 2026-09-24).
         */
        PaginaProveedorOpciones: {
            /** Items */
            items: components["schemas"]["ProveedorOpcionResponse"][];
            /** Cursor Siguiente */
            cursor_siguiente: string | null;
        };
        /** PaginaProveedores */
        PaginaProveedores: {
            /** Items */
            items: components["schemas"]["ProveedorResponse"][];
            /** Cursor Siguiente */
            cursor_siguiente: string | null;
        };
        /** PresentacionAgregarRequest */
        PresentacionAgregarRequest: {
            /** Nombre */
            nombre: string;
            /** Unidades Base */
            unidades_base: number;
            /** Usar En Venta */
            usar_en_venta: boolean;
            /** Usar En Compra */
            usar_en_compra: boolean;
        };
        /**
         * PresentacionInicialRequest
         * @description Presentación inicial dentro de un `ProductoCrearRequest` (CAT-02,
         *     CAT-03: el alta ya trae sus presentaciones, exactamente una de
         *     referencia).
         */
        PresentacionInicialRequest: {
            /** Nombre */
            nombre: string;
            /** Unidades Base */
            unidades_base: number;
            /** Usar En Venta */
            usar_en_venta: boolean;
            /** Usar En Compra */
            usar_en_compra: boolean;
            /** Es Referencia */
            es_referencia: boolean;
        };
        /** PresentacionModificarRequest */
        PresentacionModificarRequest: {
            /** Nombre */
            nombre: string;
            /** Unidades Base */
            unidades_base: number;
            /** Usar En Venta */
            usar_en_venta: boolean;
            /** Usar En Compra */
            usar_en_compra: boolean;
            /** Activo */
            activo: boolean;
        };
        /** PresentacionReferenciaCambiarRequest */
        PresentacionReferenciaCambiarRequest: {
            /**
             * Presentacion Id
             * Format: uuid
             */
            presentacion_id: string;
        };
        /** PresentacionResponse */
        PresentacionResponse: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /**
             * Producto Id
             * Format: uuid
             */
            producto_id: string;
            /** Nombre */
            nombre: string;
            /** Unidades Base */
            unidades_base: number;
            /** Usar En Venta */
            usar_en_venta: boolean;
            /** Usar En Compra */
            usar_en_compra: boolean;
            /** Es Referencia */
            es_referencia: boolean;
            /** Activo */
            activo: boolean;
            /**
             * Creado En
             * Format: date-time
             */
            creado_en: string;
            /**
             * Actualizado En
             * Format: date-time
             */
            actualizado_en: string;
        };
        /** ProductoCrearRequest */
        ProductoCrearRequest: {
            /** Codigo */
            codigo: string;
            /** Nombre */
            nombre: string;
            /**
             * Categoria Id
             * Format: uuid
             */
            categoria_id: string;
            /** Marca Id */
            marca_id?: string | null;
            /**
             * Proveedor Id
             * Format: uuid
             */
            proveedor_id: string;
            /** Unidad Base */
            unidad_base: string;
            /**
             * Alicuota Id
             * Format: uuid
             */
            alicuota_id: string;
            /** Presentaciones */
            presentaciones: components["schemas"]["PresentacionInicialRequest"][];
        };
        /** ProductoDetalleResponse */
        ProductoDetalleResponse: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Codigo */
            codigo: string;
            /** Nombre */
            nombre: string;
            /**
             * Categoria Id
             * Format: uuid
             */
            categoria_id: string;
            /** Marca Id */
            marca_id: string | null;
            /**
             * Proveedor Id
             * Format: uuid
             */
            proveedor_id: string;
            /** Unidad Base */
            unidad_base: string;
            /**
             * Alicuota Id
             * Format: uuid
             */
            alicuota_id: string;
            /** Activo */
            activo: boolean;
            /**
             * Creado En
             * Format: date-time
             */
            creado_en: string;
            /**
             * Actualizado En
             * Format: date-time
             */
            actualizado_en: string;
            /** Presentaciones */
            presentaciones: components["schemas"]["PresentacionResponse"][];
            /** Proveedor Nombre */
            proveedor_nombre: string;
        };
        /** ProductoModificarRequest */
        ProductoModificarRequest: {
            /** Codigo */
            codigo: string;
            /** Nombre */
            nombre: string;
            /**
             * Categoria Id
             * Format: uuid
             */
            categoria_id: string;
            /** Marca Id */
            marca_id?: string | null;
            /**
             * Proveedor Id
             * Format: uuid
             */
            proveedor_id: string;
            /** Unidad Base */
            unidad_base: string;
            /**
             * Alicuota Id
             * Format: uuid
             */
            alicuota_id: string;
            /** Activo */
            activo: boolean;
        };
        /**
         * ProductoResponse
         * @description Fila de listado (tarea 9.2): sin presentaciones -- para el detalle
         *     completo (incluidas sus presentaciones) ver `ProductoDetalleResponse`.
         *
         *     `proveedor_id` (change 06, contrato-api.md P1 aprobado 2026-09-24): va
         *     en el listado, el `PUT` y el detalle -- es una columna propia del
         *     producto. `proveedor_nombre`, en cambio, solo va en el detalle
         *     (`ProductoDetalleResponse`), para no llamar al puerto de ADR-025 una
         *     vez por fila de una página.
         */
        ProductoResponse: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Codigo */
            codigo: string;
            /** Nombre */
            nombre: string;
            /**
             * Categoria Id
             * Format: uuid
             */
            categoria_id: string;
            /** Marca Id */
            marca_id: string | null;
            /**
             * Proveedor Id
             * Format: uuid
             */
            proveedor_id: string;
            /** Unidad Base */
            unidad_base: string;
            /**
             * Alicuota Id
             * Format: uuid
             */
            alicuota_id: string;
            /** Activo */
            activo: boolean;
            /**
             * Creado En
             * Format: date-time
             */
            creado_en: string;
            /**
             * Actualizado En
             * Format: date-time
             */
            actualizado_en: string;
        };
        /** ProveedorCrearRequest */
        ProveedorCrearRequest: {
            /** Nombre */
            nombre: string;
            /** Cuit */
            cuit?: string | null;
            /** Contacto */
            contacto?: string | null;
            /** Telefono */
            telefono?: string | null;
            /** Email */
            email?: string | null;
        };
        /**
         * ProveedorModificarRequest
         * @description `PUT` reemplaza el estado completo (spec, `contrato-api.md` §2.1):
         *     un opcional ausente o `null` se guarda como `null`.
         */
        ProveedorModificarRequest: {
            /** Nombre */
            nombre: string;
            /** Cuit */
            cuit?: string | null;
            /** Contacto */
            contacto?: string | null;
            /** Telefono */
            telefono?: string | null;
            /** Email */
            email?: string | null;
            /** Activo */
            activo: boolean;
        };
        /**
         * ProveedorOpcionResponse
         * @description `GET /proveedores/opciones` (D8): solo proveedores activos, sin
         *     CUIT ni contacto.
         */
        ProveedorOpcionResponse: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Nombre */
            nombre: string;
        };
        /** ProveedorResponse */
        ProveedorResponse: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Nombre */
            nombre: string;
            /** Cuit */
            cuit: string | null;
            /** Contacto */
            contacto: string | null;
            /** Telefono */
            telefono: string | null;
            /** Email */
            email: string | null;
            /** Activo */
            activo: boolean;
            /**
             * Creado En
             * Format: date-time
             */
            creado_en: string;
            /**
             * Actualizado En
             * Format: date-time
             */
            actualizado_en: string;
        };
        /** RefreshRequest */
        RefreshRequest: {
            /**
             * Dispositivo Id
             * Format: uuid
             */
            dispositivo_id: string;
        };
        /** ResultadoItemLoteResponse */
        ResultadoItemLoteResponse: {
            /**
             * Operation Id
             * Format: uuid
             */
            operation_id: string;
            /** Estado */
            estado: string;
            /** Resultado */
            resultado: {
                [key: string]: unknown;
            } | null;
            /** Error Codigo */
            error_codigo: string | null;
        };
        /** RolResponse */
        RolResponse: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Nombre */
            nombre: string;
            /** Permisos */
            permisos: string[];
        };
        /** RolYoResponse */
        RolYoResponse: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Nombre */
            nombre: string;
        };
        /** RotarPinRequest */
        RotarPinRequest: {
            /** Pin */
            pin: string;
        };
        /** SaludRespuesta */
        SaludRespuesta: {
            /**
             * Estado
             * @enum {string}
             */
            estado: "ok" | "error";
        };
        /** TokenResponse */
        TokenResponse: {
            /** Access Token */
            access_token: string;
            /**
             * Token Type
             * @default bearer
             * @constant
             */
            token_type: "bearer";
        };
        /**
         * UsuarioResponse
         * @description Tarea 10.8: sin `password_hash` ni las tres columnas del PIN de
         *     autorización -- Pydantic solo serializa los campos declarados acá, así
         *     que omitirlos de este modelo es la garantía, no un filtro posterior.
         */
        UsuarioResponse: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Usuario */
            usuario: string;
            /** Nombre */
            nombre: string;
            /** Email */
            email: string | null;
            /**
             * Rol Id
             * Format: uuid
             */
            rol_id: string;
            /** Estado */
            estado: string;
        };
        /** UsuarioYoResponse */
        UsuarioYoResponse: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Nombre */
            nombre: string;
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
            /** Input */
            input?: unknown;
            /** Context */
            ctx?: Record<string, never>;
        };
        /** VersionRespuesta */
        VersionRespuesta: {
            /** Version */
            version: string;
            /** App Version Minima */
            app_version_minima?: string | null;
        };
        /**
         * YoResponse
         * @description Forma exacta del contrato aprobado el 2026-09-25 (tarea 4.1,
         *     `design.md` "Contrato de `GET /api/v1/yo`"): usuario, organización y rol
         *     (id y nombre), y la lista de permisos vigentes en orden alfabético
         *     ascendente. Nunca `usuario.usuario` (nombre de login), email, estado,
         *     secretos ni tope de descuento -- son campos que esta clase simplemente
         *     no declara, no campos excluidos al serializar (mismo criterio que
         *     `UsuarioResponse` más arriba).
         */
        YoResponse: {
            usuario: components["schemas"]["UsuarioYoResponse"];
            organizacion: components["schemas"]["OrganizacionYoResponse"];
            rol: components["schemas"]["RolYoResponse"];
            /** Permisos */
            permisos: string[];
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    salud_api_v1_salud_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SaludRespuesta"];
                };
            };
        };
    };
    version_api_v1_version_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["VersionRespuesta"];
                };
            };
        };
    };
    login_api_v1_auth_login_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["LoginRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TokenResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    refresh_api_v1_auth_refresh_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: {
                refresh_token?: string | null;
            };
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RefreshRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TokenResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    logout_api_v1_auth_logout_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: {
                refresh_token?: string | null;
            };
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    listar_dispositivos_api_v1_identidad_dispositivos_get: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DispositivoResponse"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    revocar_dispositivo_api_v1_identidad_dispositivos__dispositivo_id__delete: {
        parameters: {
            query?: never;
            header?: {
                "Operation-Id"?: string | null;
                authorization?: string | null;
            };
            path: {
                dispositivo_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    listar_usuarios_api_v1_identidad_usuarios_get: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UsuarioResponse"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    crear_usuario_api_v1_identidad_usuarios_post: {
        parameters: {
            query?: never;
            header?: {
                "Operation-Id"?: string | null;
                authorization?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CrearUsuarioRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UsuarioResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    cambiar_composicion_rol_api_v1_identidad_roles__rol_id__permisos_put: {
        parameters: {
            query?: never;
            header?: {
                "Operation-Id"?: string | null;
                authorization?: string | null;
            };
            path: {
                rol_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ComposicionRolRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RolResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    rotar_pin_autorizacion_api_v1_identidad_usuarios__usuario_id__pin_post: {
        parameters: {
            query?: never;
            header?: {
                "Operation-Id"?: string | null;
                authorization?: string | null;
            };
            path: {
                usuario_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RotarPinRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    desbloquear_usuario_api_v1_identidad_usuarios__usuario_id__desbloqueo_post: {
        parameters: {
            query?: never;
            header?: {
                "Operation-Id"?: string | null;
                authorization?: string | null;
            };
            path: {
                usuario_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    obtener_yo_api_v1_yo_get: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["YoResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    listar_categorias_api_v1_catalogo_categorias_get: {
        parameters: {
            query?: {
                limite?: number;
                cursor?: string | null;
                solo_activas?: boolean;
            };
            header?: {
                authorization?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PaginaCategorias"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    crear_categoria_api_v1_catalogo_categorias_post: {
        parameters: {
            query?: never;
            header?: {
                "Operation-Id"?: string | null;
                authorization?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CategoriaCrearRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CategoriaResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    modificar_categoria_api_v1_catalogo_categorias__categoria_id__put: {
        parameters: {
            query?: never;
            header?: {
                "Operation-Id"?: string | null;
                authorization?: string | null;
            };
            path: {
                categoria_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CategoriaModificarRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CategoriaResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    listar_marcas_api_v1_catalogo_marcas_get: {
        parameters: {
            query?: {
                limite?: number;
                cursor?: string | null;
                solo_activas?: boolean;
            };
            header?: {
                authorization?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PaginaMarcas"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    crear_marca_api_v1_catalogo_marcas_post: {
        parameters: {
            query?: never;
            header?: {
                "Operation-Id"?: string | null;
                authorization?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["MarcaCrearRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MarcaResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    modificar_marca_api_v1_catalogo_marcas__marca_id__put: {
        parameters: {
            query?: never;
            header?: {
                "Operation-Id"?: string | null;
                authorization?: string | null;
            };
            path: {
                marca_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["MarcaModificarRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MarcaResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    listar_productos_api_v1_catalogo_productos_get: {
        parameters: {
            query?: {
                limite?: number;
                cursor?: string | null;
                texto?: string | null;
                categoria_id?: string | null;
                marca_id?: string | null;
                activo?: boolean | null;
            };
            header?: {
                authorization?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PaginaProductos"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    crear_producto_api_v1_catalogo_productos_post: {
        parameters: {
            query?: never;
            header?: {
                "Operation-Id"?: string | null;
                authorization?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ProductoCrearRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProductoDetalleResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    obtener_producto_api_v1_catalogo_productos__producto_id__get: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path: {
                producto_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProductoDetalleResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    modificar_producto_api_v1_catalogo_productos__producto_id__put: {
        parameters: {
            query?: never;
            header?: {
                "Operation-Id"?: string | null;
                authorization?: string | null;
            };
            path: {
                producto_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ProductoModificarRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProductoResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    agregar_presentacion_api_v1_catalogo_productos__producto_id__presentaciones_post: {
        parameters: {
            query?: never;
            header?: {
                "Operation-Id"?: string | null;
                authorization?: string | null;
            };
            path: {
                producto_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PresentacionAgregarRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PresentacionResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    modificar_presentacion_api_v1_catalogo_presentaciones__presentacion_id__put: {
        parameters: {
            query?: never;
            header?: {
                "Operation-Id"?: string | null;
                authorization?: string | null;
            };
            path: {
                presentacion_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PresentacionModificarRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PresentacionResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    cambiar_referencia_api_v1_catalogo_productos__producto_id__referencia_put: {
        parameters: {
            query?: never;
            header?: {
                "Operation-Id"?: string | null;
                authorization?: string | null;
            };
            path: {
                producto_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PresentacionReferenciaCambiarRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PresentacionResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    listar_alicuotas_api_v1_configuracion_alicuotas_get: {
        parameters: {
            query?: {
                limite?: number;
                cursor?: string | null;
            };
            header?: {
                authorization?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PaginaAlicuotas"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    listar_proveedores_api_v1_proveedores_get: {
        parameters: {
            query?: {
                limite?: number;
                cursor?: string | null;
                texto?: string | null;
                activo?: boolean | null;
            };
            header?: {
                authorization?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PaginaProveedores"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    crear_proveedor_api_v1_proveedores_post: {
        parameters: {
            query?: never;
            header?: {
                "Operation-Id"?: string | null;
                authorization?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ProveedorCrearRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProveedorResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    obtener_proveedor_api_v1_proveedores__proveedor_id__get: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path: {
                proveedor_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProveedorResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    modificar_proveedor_api_v1_proveedores__proveedor_id__put: {
        parameters: {
            query?: never;
            header?: {
                "Operation-Id"?: string | null;
                authorization?: string | null;
            };
            path: {
                proveedor_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ProveedorModificarRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProveedorResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    listar_opciones_de_proveedores_api_v1_proveedores_opciones_get: {
        parameters: {
            query?: {
                limite?: number;
                cursor?: string | null;
            };
            header?: {
                authorization?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PaginaProveedorOpciones"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    informar_costos_api_v1_costos_post: {
        parameters: {
            query?: never;
            header?: {
                "Operation-Id"?: string | null;
                authorization?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CostoInformarRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CostoInformarResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    obtener_costo_vigente_api_v1_costos_productos__producto_id__vigente_get: {
        parameters: {
            query?: {
                fecha?: string | null;
            };
            header?: {
                authorization?: string | null;
            };
            path: {
                producto_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CostoVigenteResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    listar_historial_de_costos_api_v1_costos_productos__producto_id__historial_get: {
        parameters: {
            query?: {
                limite?: number;
                cursor?: string | null;
            };
            header?: {
                authorization?: string | null;
            };
            path: {
                producto_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PaginaCostosInformados"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    sincronizar_lote_api_v1_sync_comandos_post: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["LoteComandosRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LoteComandosResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
}
